name: flutterdemo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #国际化
  flutter_localizations:
    sdk: flutter

  #English words
  english_words: ^4.0.0

  #Cached network image
  cached_network_image: ^3.0.0

  #透明占位符
  transparent_image: ^2.0.0

  #websocket
  web_socket_channel: ^2.1.0

  #Http
  http: ^0.13.3

  #SharedPreference
  shared_preferences: ^2.0.6

  #A Flutter plugin for finding commonly used locations on the filesystem.
  #Supports iOS and Android.
  path_provider: ^2.0.2

  #Sqlite
  sqflite: ^2.0.0+3

  #camera
  #camera: ^0.5.7+2

  #创建适配任何平台的路径
  path: ^1.8.0

  #视频播放
  video_player: ^2.1.6

  # 使用Intl国际化
#  intl: ^0.16.1
#  intl_translation: ^0.17.9

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
    - images/pic4.jpg
    - images/pic5.jpg
    - images/pic6.jpg
    - images/pavlova.jpg

  fonts:
    - family: Raleway
      fonts:
        - asset: lib/fonts/Raleway-Regular.ttf
        - asset: lib/fonts/Raleway-Italic.ttf
          style: italic

    - family: DancingScript
      fonts:
        - asset: lib/fonts/DancingScript-Regular.ttf
        - asset: lib/fonts/DancingScript-Bold.ttf

    - family: Pacifico
      fonts:
        - asset: lib/fonts/Pacifico-Regular.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

